routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account

collections:
  /:
    permalink: /{slug}/
    template: index
  /tutorials/:
    permalink: /tutorials/{slug}/
    template: index
    filter: primary_tag:tutorials

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
